name: DevSecOps CI Pipeline

on:
  workflow_dispatch:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Checkout App Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2️⃣ Setup Node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3️⃣ Install Dependencies
    - name: Install Dependencies
      run: npm install

    # 4️⃣ SonarQube Scan
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # 5️⃣ Build React App
    - name: Build React App
      run: |
        CI=false npm run build

    # 6️⃣ Set Docker Image Tag
    - name: Set Image Tag
      run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

    # 7️⃣ Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 8️⃣ Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/swiggy:${{ env.IMAGE_TAG }} .

    # 9️⃣ Trivy Scan
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/swiggy:${{ env.IMAGE_TAG }}
        format: table
        exit-code: 1
        severity: HIGH,CRITICAL

    # 🔟 Push Docker Image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/swiggy:${{ env.IMAGE_TAG }}

    # 1️⃣1️⃣ Checkout GitOps Repo
    - name: Checkout GitOps Repo
      uses: actions/checkout@v3
      with:
        repository: Devendrasaini1441/DevSecOps-GitOps-Repo
        token: ${{ secrets.GITOPS_TOKEN }}
        path: gitops

    # 1️⃣2️⃣ Update Image Tag in Deployment YAML
    - name: Update Image Tag
      run: |
        sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/swiggy:${{ env.IMAGE_TAG }}|g" gitops/deployment.yaml

    # 1️⃣3️⃣ Commit and Push Changes
    - name: Commit and Push to GitOps Repo
      run: |
        cd gitops
        git config user.name "Devendrasaini1441"
        git config user.email "devsaini1441@gmail.com"
        git add .
        git commit -m "Update image to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
        git push
